services:
  db:
    image: postgres:15-alpine
    container_name: comic-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: comic_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  redis:
    image: redis:7-alpine
    container_name: comic-redis
    ports:
      - "6379:6379"
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: comic-api
    depends_on:
      - redis
      - db
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      GLOBAL_PREFIX: ${GLOBAL_PREFIX}
      CORS_ENABLED: ${CORS_ENABLED}
      CORS_ORIGINS: ${CORS_ORIGINS}
      APP_TIMEZONE: ${APP_TIMEZONE}

      DATABASE_URL: ${DATABASE_URL}
      DIRECT_URL: ${DIRECT_URL}
      REDIS_URL: ${REDIS_URL}
      CACHE_DRIVER: ${CACHE_DRIVER}

      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}

      STORAGE_TYPE: ${STORAGE_TYPE}
      STORAGE_S3_BUCKET: ${STORAGE_S3_BUCKET}
      STORAGE_S3_ACCESS_KEY_ID: ${STORAGE_S3_ACCESS_KEY_ID}
      STORAGE_S3_SECRET_ACCESS_KEY: ${STORAGE_S3_SECRET_ACCESS_KEY}
      STORAGE_S3_REGION: ${STORAGE_S3_REGION}
      STORAGE_S3_ENDPOINT: ${STORAGE_S3_ENDPOINT}
      STORAGE_S3_FORCE_PATH_STYLE: ${STORAGE_S3_FORCE_PATH_STYLE}
      STORAGE_S3_BASE_URL: ${STORAGE_S3_BASE_URL}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}
      GOOGLE_FRONTEND_URL: ${GOOGLE_FRONTEND_URL}

      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
    ports:
      - "8000:8000"

volumes:
  db_data:
